### ISSUE TITLE
German umlauts do not work in some menu buttons.

### ISSUE THREAD

**Issue by tafode** [notapixelstudio/superstarfighter#1069]
In some of the option menus the back button doesn't show umlauts. e.g. in the options menu, the button only shows. "ZURCK" instead of "ZURÜCK". Same issue in the audio menu. I'm new in the Godot Engine, so I'm not totally sure, but I guess it has todo with a different font which does not support umlauts.

![Option](https://user-images.githubusercontent.com/17379814/222932913-06b7e953-f3ca-4e79-a449-3bf700e20319.PNG)
![Audio](https://user-images.githubusercontent.com/17379814/222932914-3add83a8-3396-4129-b8b2-71c7b641f9b0.PNG)

**Comment by salvob41** [comment]
Thank you for the report.

Yes, it has to do with the font used that does not have the special character.

The localization is still the one from the previous release so it's missing a few labels and wasn't test properly.

We need to work on it and fix it. Should be enough to use and decide a fallback font.

**Comment by salvob41** [comment]
https://github.com/godotengine/godot/issues/8998#issuecomment-544190708

Relevant

**Comment by tafode** [comment]
You're welcome. I have also tried to fix/add some of the missing strings in the german localization file with the pull request [here](https://github.com/notapixelstudio/superstarfighter/pull/1068) . But I did realize that the file is not uptodate, e.g. Start instead of new game... So I wasn't sure what is still used and what not.

**Comment by salvob41** [comment]
True, a lot of different improvements have been added in starship Olympics. And we haven't yet focus on reporting those changes in localization, also because they might soon change again depending on the feedback and clarity perceived by users. 

Thanks, this is important for us.

**Comment by tafode** [comment]
Hi again,

The issue with the menu buttons is fixed. But I just noticed that there is another place where the umlauts are not displayed correctly.

![CharacterScreen](https://user-images.githubusercontent.com/17379814/224845590-09e8a5e2-241c-44ca-ab64-9f4a8597731b.png)

The name of the species should most likely be no problem, as I guess they will stay the same as the english one. But the description of the Aurels has already umlauts in the german text. Should be "überfürsorgliche Hirten". I hope this is something which don't cause too much effort.

**Comment by salvob41** [comment]
True, I made a fix for this, but we should keep checking since the resources for the fonts contains information different depending on which label we are dealing with. I know that in Godot4 they changed this behaviour. 
So next release we will update this specific issue, but I'll keep this open until we add fallback to ALL labels (and buttons)
