### ISSUE TITLE
Issues with translating tutorial texts

### ISSUE THREAD

**Issue by tafode** [notapixelstudio/superstarfighter#1128]
I tried to translate the tutorial texts into German, but I'm facing some issues.

First, I'm not sure if it is the best idea to have the strings like "MOVE" and "MOVE +". Maybe it would make more sense to just have MOVE in one label and the + in another one. So it doesn't need to be translated in 2 strings. The same is true for "CHARGE AND DASH" and "CHARGE AND DASH +".

After translating the strings I realized that if the translated text is bigger than the original English one, it can lead to issues like this:
![String_5](https://user-images.githubusercontent.com/17379814/236573454-ac597218-ce24-41df-8d24-2cd362c7140d.PNG)
![string_4](https://user-images.githubusercontent.com/17379814/236573550-cbaf62b7-3c4e-4ea6-a979-6fafa3d86f66.jpg)

Maybe there is a way to allow longer texts in the tutorial screen without breaking the layout.

**Comment by nitaku** [comment]
You are absolutely right, these tutorial screens were put up together in a hurry, and they don't support texts of different sizes.
We plan to implement a radically different tutorial screen in upcoming versions of the game though. Let's keep the current tutorial as it is for the moment. The new one will support multiple languages.
