### ISSUE TITLE
Project structure documentation / guides

### ISSUE THREAD

**Issue by ilionic** [notapixelstudio/superstarfighter#1142]
I am learning Godot and this is probably the biggest open source project I saw. Impressive work and amount of content created! 
Would be very helpful to outline top level project organisation and structure. 
I guess this could also help open source contributions and beginners. Thanks!

**Comment by nitaku** [comment]
Hi @ilionic , sorry for the late reply.

You are perfectly right about all the stuff you mentioned, we are trying to get some documentation done as we port the game to Godot 4 (still a work in progress and a daunting task for us). We hope that the new resulting codebase will be more welcoming to contributors and Godot beginners.

That said, this is our first non-jam game ever, and we are still learning Godot and gamedev ourselves (in our spare time). So I would not recommend our code as a learning resource, especially as messy and undocumented as it is now.

While you wait for us to clean the codebase up (fingers crossed), you can head to [GDQuest's website](https://www.gdquest.com/), where you should find code examples, lessons and a full game source (maybe the latter is just for paying members, I don't remember).

**Comment by ilionic** [comment]
Thanks!
GDQuest is nice, but sometimes curiosity pushes outside of small scoped tutorials comfort zone, hence was curious how bigger project like yours is structured.
Good luck with Godot4 migration!
