### ISSUE TITLE
AI - performance issue

### ISSUE THREAD

**Issue by salvob41** [notapixelstudio/superstarfighter#128]
In order to calculate where the ship is supposed to go. We need to calculate for every frame the angle of some unit vectors. That is computational challenging.

Let's try to do something like:
```
float sinvalues[] = new float[360];
float cosvalues[] = new float[360];
for (int i = 0; i < 360; i++) {
  sinvalues[i] = sin(radians(i));
  cosvalues[i] = cos(radians(i));
}
```

**Comment by nitaku** [comment]
Are you sure that Godot doesn't already do any optimization like that?

**Comment by salvob41** [comment]
No, I am not sure. 
But my computer van explodes when the scenes with AI ships starts

**Comment by salvob41** [comment]
FAN* not van :D

**Comment by nitaku** [comment]
Please, I want to see your computer van! :D

**Comment by salvob41** [comment]
The problem is not this
