### ISSUE TITLE
Make logos

### ISSUE THREAD

**Issue by salvob41** [notapixelstudio/superstarfighter#14]

**Comment by salvob41** [comment]
- Iniziamo da questo articolo dei loghi ... molto interessante ... pero' è figo ...  non deve essere per forza cosi' pero' rimanda ad idee.  https://qz.com/755251/on-a-scale-from-1-100-milton-glaser-rates-every-single-olympic-logo-design-in-history/  (Qui si vedono tutti: 
![image](https://user-images.githubusercontent.com/6097015/55194490-1e878980-51aa-11e9-8dcf-0a33af5068a5.png) 


- Altra cosa che potrebbe essere interessante è il logo del Triathlon: 
![image](https://user-images.githubusercontent.com/6097015/55194421-e6804680-51a9-11e9-911e-8a58635057c1.png)

- Studio dell'eventuale logo di Tokyo 2022: 
![image](https://user-images.githubusercontent.com/6097015/55194446-fdbf3400-51a9-11e9-85c4-5e306d3b6197.png)

- I font possono essere d'aiuto parecchio: - https://www.1001fonts.com/science-fiction-fonts.html?page=13&items=10
Questo font qui ad esempio: 
![image](https://user-images.githubusercontent.com/6097015/55194588-71614100-51aa-11e9-97f1-1136ff519cd8.png)
I font "appetibili" sono qui: https://github.com/notapixelstudio/superstarfighter/tree/master/godot/assets/fonts

- D'altra parte anche uno pseudo logo/banner andrebbe bene: Tipo 
![image](https://user-images.githubusercontent.com/6097015/55194762-dc127c80-51aa-11e9-88c1-b158bde72ffd.png)
![image](https://user-images.githubusercontent.com/6097015/55194778-e6347b00-51aa-11e9-9755-211c49ecbdbd.png)
![image](https://user-images.githubusercontent.com/6097015/55194822-fc423b80-51aa-11e9-94ec-29eee678395e.png)
![image](https://user-images.githubusercontent.com/6097015/55194856-0c5a1b00-51ab-11e9-8b3f-0d39a206111b.png)
![image](https://user-images.githubusercontent.com/6097015/55194891-28f65300-51ab-11e9-8395-202bba1eadf7.png)

**Comment by salvob41** [comment]
ah e poi c'è piu' o meno quello che per ora usiamo come logo: 
![image](https://user-images.githubusercontent.com/6097015/55195079-be91e280-51ab-11e9-841b-d87fccf6cc22.png)

**Comment by nitaku** [comment]
Quello era più che altro uno studio... poi è rimasto XD

**Comment by salvob41** [comment]
Some examples of sports logo

![image](https://user-images.githubusercontent.com/6097015/55324413-3d27a200-5482-11e9-8ae7-e57c0e931ce5.png)

**Comment by salvob41** [comment]
https://www.pinterest.com/pin/461056080577458619/
[![image](https://user-images.githubusercontent.com/6097015/55544530-93d3ec80-56cb-11e9-8326-084db40e8ce2.png)](https://www.pinterest.com/pin/461056080577458619/)

varie immagini utili come ispirazione per la grafica in-game
neon style, retro 80's
forse può essere utile anche per il logo, insieme alle cose sportive
come se i giochi arcade fossero sport

**Comment by salvob41** [comment]
![image](https://user-images.githubusercontent.com/6097015/56306522-f48b0c80-6142-11e9-986b-b43358e4d468.png)

diversi loghi sportivi hanno una palla
che sfreccia
tra l'altro riconoscibile da sport a sport
noi abbiamo la bomba
nel fare un logo lo terrei in considerazione
io ci vedevo la nave che lancia la bomba...
