### ISSUE TITLE
Players should not choose same species

### ISSUE THREAD

**Issue by salvob41** [notapixelstudio/superstarfighter#16]
If the two players are selecting the same characters:
![image](https://user-images.githubusercontent.com/6097015/45094576-02dc6900-b11c-11e8-91ee-bbb674cddb99.png)

whenever one of them choose , the other could choose same species:
![image](https://user-images.githubusercontent.com/6097015/45094614-18519300-b11c-11e8-803e-08007bab1ab7.png)

and the second player can do this:
![image](https://user-images.githubusercontent.com/6097015/45094642-24d5eb80-b11c-11e8-9cd2-b79f44f8b633.png)

**Comment by nitaku** [comment]
as soon as a species is selected, it should be removed from the available choices for other players

**Comment by salvob41** [comment]
it is. But the selection is still there and the state might be in an awkward situation. Need attention. 
But if we want to modify the structure of global, might be a good idea to fix this in hindsight.

**Comment by salvob41** [comment]
Reopen this because of new refactoring. Need a fix

**Comment by salvob41** [comment]
![screenshot 2018-12-21 at 19 11 27](https://user-images.githubusercontent.com/6097015/50356919-42f11b80-0554-11e9-96b5-35f088420e9d.png)
