### ISSUE TITLE
Spawning inside a hostile field is broken

### ISSUE THREAD

**Issue by nitaku** [notapixelstudio/superstarfighter#193]
When the invulnerability wears off, the ship is not checked again for entering the field and it is not killed. This can be avoided reimplementing this check as continuous + timeout.

**Comment by salvob41** [comment]
It does happen also in crown mode: if you get the crown when you are inside the no-crown-zone

**Comment by nitaku** [comment]
This is not relevant anymore, we do not use hostile fields anymore
