### ISSUE TITLE
Wall geometry might be more user friendly with rect extents gizmo

### ISSUE THREAD

**Issue by salvob41** [notapixelstudio/superstarfighter#194]
https://www.youtube.com/watch?v=nSqaIY-eJm0

**Comment by nitaku** [comment]
That would be nice. I'll take a look into it when I come back to develop the geometry plugin further.

**Comment by henriiquecampos** [comment]
@nitaku do you need anything too specific? The Plugin made by Nathan is [available on OpenRPG repo](https://github.com/GDquest/godot-open-rpg/tree/master/godot/addons/rect_extents_gizmo)

Give me a heads up if you need any help with plugins, I will be glad to give you all a hand :grin:

**Comment by nitaku** [comment]
Thank you @henriiquecampos :)
We currently have a working geometry plugin that fits our needs. It is currently lacking any kind of on-canvas editing, so we are stuck with inputting numbers in the editor for now.
This is what we have:
A) Pure geometry nodes with no other functionality attached (i.e., no collisions nor graphics)
B) Special shapes needed in our game (beveled rectangles, regular polygons, ellipses...)
C) A buggy and repetitive boilerplate code we use in nodes that need to update whenever a child geometry node is modified

We could really use your help in fixing point C, or in adding on-canvas editing. There's a hope that our internal plugin would be of use for other people :D

**Comment by nitaku** [comment]
This is an example from the game, the outside wall of the arena is defined like this:

![image](https://user-images.githubusercontent.com/1604569/59340833-0d5d0c00-8d07-11e9-863e-7470b89fd539.png)

The yellow node defines the geometry with the following parameters: `width`, `height`, and `bevel`. The wall makes use of the aforementioned boilerplate code to update itself whenever the geometry node is updated.

This works with the animation player as well! In this specific level, the outside wall is animated such that its corners shrink and grow. This is done by controlling the `bevel` parameter of the geometry via the animation player.

**Comment by henriiquecampos** [comment]
> We currently have a working geometry plugin that fits our needs. It is currently lacking any kind of on-canvas editing, so we are stuck with inputting numbers in the editor for now.

Had you check my [`Geometry2D`](https://github.com/pigdevstudio/godot_tools/blob/1ed17678417426d2e425effad4989f56d336d25e/source/utility_nodes/Geometry2D.gd)? It is a tool script that draws `Shape2D`. It is not meant for release/production, but it does helps in pre-preduction and design.

**Comment by nitaku** [comment]
Yeah, we considered using it, and definitely will use it for prototyping games! Great work :)

But in this game we needed more types of shapes, sometimes without collision, sometimes without graphics. So we created our plugin. It would be nice to add handles and such to control our shapes though.

**Comment by nitaku** [comment]
Currently out of scope.
