### ISSUE TITLE
New GShape doesn't show in editor

### ISSUE THREAD

**Issue by nitaku** [notapixelstudio/superstarfighter#196]
Need to find a way to update the editor whenever the GShape is added.

**Comment by salvob41** [comment]
https://github.com/notapixelstudio/superstarfighter/blob/252caf0a71c6b07b597147ab5617df2fc419c435/godot/addons/geometry/GShape.gd

you should add here something like: 
```
func _ready():
    get_parent().refresh()
```

**Comment by nitaku** [comment]
I think it could work, but parent nodes are not required to implement a refresh method...

**Comment by salvob41** [comment]
Mm.. signal is the way then
