### ISSUE TITLE
Ship death animation

### ISSUE THREAD

**Issue by nitaku** [notapixelstudio/superstarfighter#211]
Solves camera tracking, not losing sight of your ship, trails particles not clearing, death sfx, and additional visual feedback when hitting deadly walls.

**Comment by salvob41** [comment]
let's make another object

**Comment by salvob41** [comment]
Starting and addressed in https://github.com/notapixelstudio/superstarfighter/pull/242/commits/fc4cd9b2f1402bf9210065e1ee8907e3852ade01 

Will need a proper animation though
