### ISSUE TITLE
new species: psychic aalien

### ISSUE THREAD

**Issue by salvob41** [notapixelstudio/superstarfighter#213]
An idea of a new species could be some sort of psychic species that have portals, teleporting and stuff. 

and I imagined them as a sort of mix of these things:
![image](https://user-images.githubusercontent.com/6097015/54426149-6b358400-4717-11e9-8aff-92343e0c4fa9.png)
![image](https://user-images.githubusercontent.com/6097015/54426155-6ec90b00-4717-11e9-8d69-4e8bb8c4c92b.png)
![image](https://user-images.githubusercontent.com/6097015/54426168-74265580-4717-11e9-9458-087cc275c648.png)

**Comment by nitaku** [comment]
![photo5791737290006048688](https://user-images.githubusercontent.com/1604569/54426541-6b824f00-4718-11e9-99d6-d60b074f2b30.jpg)
I first thought about a portal-making species a while ago, after seeing this image. Let's throw it into the mix! :)

**Comment by nitaku** [comment]
I envisioned they would have an ethereal appearance, and space-dyed clothing. They have the ability to manipulate space itself, but while they are almost godlike and detached, their psychological attitude is relaxed and reassuring. Their tagline is "optimistic nihilists" (cit.).
