### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by urtzai** [notapixelstudio/superstarfighter#259]
Any plan to translate this game to different languages? I would appreciate to have a localization option.

Thanks!

**Comment by Calinou** [comment]
By the way, note that you can use gettext files for localization instead of CSV. This could work better in a project where people may be contributing to multiple languages as a given time, as each language will be in its own file. See the [documentation](https://docs.godotengine.org/en/latest/tutorials/i18n/localization_using_gettext.html) for more information.

**Comment by salvob41** [comment]
Hey @urtzai , Sure! we would like to have the game translated in as many languages as possibile. Which language did you have in mind? 
You can help us out trying to put everything in place, what do you think ? 

Thank you @Calinou for the insight, we need to adapt the code for this, but won't be much difficult

You can join our discord and we can talk about improvements there:  https://discord.gg/XFKAT4f

**Comment by urtzai** [comment]
Thank you @Calinou and @salvob41 for your comments! I made my first pull-request to this project. I will put here all the issues I find, testing images/videos and make some suggestions related to the localization.

Thank you!

**Comment by urtzai** [comment]
Hi, these are the improvements to be done I've detected when I was localizing the game:

- Need of language selector in the options menu.

![2019-07-05 11-48-21-ko-pantaila-argazkia](https://user-images.githubusercontent.com/1741252/60714483-75280080-9f1b-11e9-8802-3f9ac15b3e2d.png)

- Graphic elements sizing depending of the string (use flexible containers?)

![2019-07-05 11-47-26-ko-pantaila-argazkia](https://user-images.githubusercontent.com/1741252/60714604-a9032600-9f1b-11e9-9672-020a96d12f26.png)

- Some strings are divided in two elements (e.g. tagline 1 and tagline 2). In some languages these two strings have to be joined to have a correct translation. For example in basque.

The good translation would be:

playful = jostalaria
slaughterers = hiltzaileak

But when this two words are going together, the order and the plural changes to have a sense: 

playful slaughterers = hiltzaile jostalariak

So the tricky way to do this is, changing the order and plural:

![2019-07-05 11-58-18-ko-pantaila-argazkia](https://user-images.githubusercontent.com/1741252/60714957-41010f80-9f1c-11e9-9323-839448ff5283.png)

**Comment by nitaku** [comment]
@urtzai @Calinou Thanks for your contributions! We plan to integrate the internationalization support during this weekend. :)

**Comment by salvob41** [comment]
Well, I did merge on master the skeleton for the Internationalisation... 

Some things on the UI changed so I had to update the template that @urtzai first made. But I had to do it manually (is there a tool in which you can update the `.po` files?) . 

Graphics elements now are dynamically resizable. ✔️ 

> Some strings are divided in two elements (e.g. tagline 1 and tagline 2). In some languages these two strings have to be joined to have a correct translation. For example in basque.

I did simplified this.. Now there is just one tagline. ✔️  

> Need of language selector in the options menu.

This is a bit more complicated, because we got rid of the buttons and the options menu (since it was empty). An idea might be to let you choose the language when the game starts. What do you guys think ?

**Comment by Calinou** [comment]
> Some things on the UI changed so I had to update the template that @urtzai first made. But I had to do it manually (is there a tool in which you can update the .po files?) .

You can update PO files using the `msgmerge` command-line tool: https://docs.godotengine.org/en/latest/tutorials/i18n/localization_using_gettext.html#updating-message-files-to-follow-the-po-template

**Comment by urtzai** [comment]
Thank you it looks really good!!

> Some things on the UI changed so I had to update the template that @urtzai first made. But I had to do it manually (is there a tool in which you can update the .po files?) .

When I first extracted the strings I also did manually.

> This is a bit more complicated, because we got rid of the buttons and the options menu (since it was empty). An idea might be to let you choose the language when the game starts. What do you guys think ?

mmm but I still think the menu is important when the game starts. At least to have a "quit game", "music volume", "graphic options", some kind of "game mode" (practice, single [only one battle quickplay? ], tournament... whatever) or language options.

And I think also, would be nice to be able to choose the game mode (deathmatch, take the crown...) without being "random"...

But maybe this discussion may have to take place in another thread.

**Comment by nitaku** [comment]
We are currently wondering about game modes (practice, tournament, etc.) and selecting the "sport" to play (deathmatch, take the crown, etc.).

The design is still in its early stages, but feel free to elaborate on those ideas (maybe the #feedback channel in our Discord is better suited for that).

**Comment by salvob41** [comment]
I'll be closing this for now. 

I will open related issues for the rest of the points touched in this conversation
