### ISSUE TITLE
Unlocking

### ISSUE THREAD

**Issue by salvob41** [notapixelstudio/superstarfighter#282]
Since we would like to unlock some species after playing we could easily implement a standalone scene that might be used when we expand this feature

**Comment by ekorina** [comment]
Maybe it's more an unlocking *system* with a lot of animations rather than a standalone scene. It could heavily use the map scene, connecting new paths between sets as in Super Mario Brothers games.

**Comment by salvob41** [comment]
what about unlocking new species... or new characters?

**Comment by ekorina** [comment]
I think the map could be used for that as well. Maybe it could contain more content rather than just sets and options. I am thinking for example about a "boss" level to be played in co-op that unlocks the corresponding race when defeated.

**Comment by salvob41** [comment]
In #575 we implemented the Unlocking system. Of course will need lots of tweaks. But If anything occurs we'll open a new issue. Thanks
