### ISSUE TITLE
Snake the crown vs CPU: crashed 

### ISSUE THREAD

**Issue by dlgltlzed** [notapixelstudio/superstarfighter#309]
Game crashed while playing on Ubuntu 18.04.
Log attached.
[Startfighter-Crash-Log.txt](https://github.com/notapixelstudio/superstarfighter/files/3907149/Startfighter-Crash-Log.txt)

**Comment by salvob41** [comment]
Thanks for the crash report. 
I backtracked the error thanks to your log. 

You were playing the build v0.5.0 from the itch.io . And you were playing in single player vs the CPU. 

The game might crash when in "Snake the Crown mode" if the CPU was holding the crown and the player dies. It need some work. 

We are going to fix this in v0.6.

**Comment by salvob41** [comment]
The game has been heavily reengineered, and CPU ships don't work as they used to. 

This technically has not been fixed, but since the behaviour now is quite differently, I am going to close this
