### ISSUE TITLE
Invalid index for available_languages dictionary on game launch

### ISSUE THREAD

**Issue by giusdp** [notapixelstudio/superstarfighter#310]
OS: Windows 10
Godot: 3.1.2
When i launch the game the value passed to
```
func _set_language(value:String):
	language = value
	TranslationServer.set_locale(available_languages[language])
```
 in res://globals/global.gd on line 26
is "italian", which throws an exception at` available_languages[language]` (the available_languages has "italiano" as a key, not "italian").

If I change the key to italian it works of course and i can access the menu, but if i go to change the language in the game it throws the same exception for italian but not for the other languages.

**Comment by salvob41** [comment]
it was a small change to made, but I couldn't find the time to replicate the issue, and therefore fix it, before. 

Thank you! This was a nasty one, now should be more robust
