### ISSUE TITLE
Configurable control style

### ISSUE THREAD

**Issue by nitaku** [notapixelstudio/superstarfighter#322]
At the moment, the game supports two different control styles:

1) absolute movement - the ship moves towards the direction of the analog stick
2) relative movement (a.k.a. "tank" mode) - the ship steers left or right when keyboard or d-pad buttons are pressed

The vast majority of players finds the relative movement unintuitive, but there's a small group that tends to like it. In addition, relative movement makes the game harder to play, offering an extra challenge.

It seems that letting players choose which style to use could be a good solution.

**Comment by salvob41** [comment]
I am not sure this is still a way we can go on. I would say not

**Comment by nitaku** [comment]
I concur. It is too much effort for now, maybe we'll revisit it when we'll finish implementing controls for accessibility.
