### ISSUE TITLE
Consider giving each player a star when a tie is made

### ISSUE THREAD

**Issue by nitaku** [notapixelstudio/superstarfighter#401]
Unless the score is zero. Check if it applies well to all minigames.

**Comment by nitaku** [comment]
What if the session results in a draw? Comparing purple stars with yellow ones aside, we should continue playing matches until the tie is broken.

**Comment by salvob41** [comment]
What if in a game of 4 people, the tie is between 2. Do the others have a chance of continuing it?

**Comment by nitaku** [comment]
No, I don't think so. If two or more players would win the session with the same amount of stars, those players (and those alone) should be given a new match to play for breaking the tie.

**Comment by nitaku** [comment]
It seem to be a bad choice after all. Closing after playtest II.
