### ISSUE TITLE
Portal is bugged. Offset and entered/exited from portal causes trouble

### ISSUE THREAD

**Issue by salvob41** [notapixelstudio/superstarfighter#417]
@ekorina is all yours

**Comment by ekorina** [comment]
I think that in addition, portals and walls do not work well together. I believe that it could be useful to implement a portal that could be crossed from one side, and that it's solid from the other. I'm onto it.

**Comment by ekorina** [comment]
It seems that implementing a one-way portal with one-way collision shapes is way harder than it seems. Maybe I'll try to come up with a new idea...

**Comment by ekorina** [comment]
Closed in #434
