### ISSUE TITLE
Wrong colors of score bars in crown

### ISSUE THREAD

**Issue by nitaku** [notapixelstudio/superstarfighter#502]

**Comment by ekorina** [comment]
Also in survival. Likely a timing issue.

**Comment by nitaku** [comment]
Don't know way this fixes survival too, but it seems gone as we fixed self-stealing.

**Comment by nitaku** [comment]
It came back XD Possibly related to self-stealing and #589

**Comment by nitaku** [comment]
Godot version should be at least 3.2.4. The error is there only if the game is executed from Godot 3.2.3
