### ISSUE TITLE
Levels

### ISSUE THREAD

**Issue by salvob41** [notapixelstudio/superstarfighter#52]
In order to fairly play in more players, we need level design. The idea is that all the ships are equally distant from each other

**Comment by salvob41** [comment]
In order to create new levels and attach them to the superstarfighter cycle (Selection-combat-gameover), we need to pay attention to a few small things: 

1. Here we call the arena, depending on how many contestants are joining in: 
https://github.com/notapixelstudio/superstarfighter/blob/1ef9fd376ea9811cf4caddc4867719b4cb0f5933/local_multiplayer/LocalMultiplayer.gd#L56
2. In the folder `combat/levels` there are all the arenas available. The name logic is: 
`<X>players.tscn` 
If we want to add new levels for `X` players I would call it something like `<X>players_<index>.tscn` where `<index>` is an ID for the new levels
3. Remember to put this logic in the line highlighted in point 1

**Comment by salvob41** [comment]
moved to next milestone. Need development and playtest

**Comment by nitaku** [comment]
Closing this issue because now there are some levels to play with and a level selection UI. We'll come back to level design and level selection in dedicated issues.
