### ISSUE TITLE
Put chosen controls and Species in SpawnerPlayer

### ISSUE THREAD

**Issue by salvob41** [notapixelstudio/superstarfighter#59]
You could do something like:
Create a scene: PlayerSpawner.tscn with a script that take `export (String) var controls = "kb1"` and `export (Resource) var species`
Take the resources from res://actors/battlers/characters
In Arena.gd link the resource and the controls from SpawnerPlayer to the Ship (around line 52)

**Comment by nitaku** [comment]
Done in #61

**Comment by salvob41** [comment]
let's close this one when the PR is merged :)
