### ISSUE TITLE
Test new movement / physics

### ISSUE THREAD

**Issue by nitaku** [notapixelstudio/superstarfighter#643]
- [ ] Dash
  - [x] Is megadash fun?
  - [x] Do we wait for too long before starting a dash?
  - [ ] Is excessive dash spamming gone? Do players miss it?
- [ ] General feel
  - [x] New ship size, is there enough space?
  - [x] Do controls feel slippery?
  - [ ] Is movement FPS-dependent?
- [x] Aim
  - [x] Is fine/coarse rotation good?
  - [x] Are "circling the square" controls good?

**Comment by nitaku** [comment]
Controls do feel too slippery (opened #655).

**Comment by salvob41** [comment]
I will leave this opened. This might be interesting. 
Most of those have actually been tackled. But still, some points are really important

**Comment by nitaku** [comment]
"New ship size, is there enough space?" was a very good question, since it wasn't in fact enough space. We fixed it though.

**Comment by salvob41** [comment]
oopsie, well... I'll reopen it

**Comment by nitaku** [comment]
There's no need, I copied it as a playtest note. You can find those in the fourth column of the 0.9 project
