### ISSUE TITLE
Test set cohesion / variety

### ISSUE THREAD

**Issue by nitaku** [notapixelstudio/superstarfighter#644]
- [ ] Sets. Do players...
  - [ ] ...express preference to some sets?
  - [ ] ...remember the content of a set?
  - [ ] ...recognize a minigame from its minicard?
  - [ ] ...choose always the same set / core / a new set?
  - [ ] ...choose a set that's already picked by another player?
  - [ ] ...choose a different set if they lost?
  - [ ] ...think that they are better at playing certain sets? Do they choose them?
- [ ] Is the unlocking minicard animation useful to...
  - [ ] ...make players curious about new games?
  - [ ] ...help players remember new games?

**Comment by salvob41** [comment]
No sets anymore. 
Sets are dead, Long live the game
