### ISSUE TITLE
Support multiple resolutions in options

### ISSUE THREAD

**Issue by nitaku** [notapixelstudio/superstarfighter#651]
the game could be quite heavy on high dpi screens and with lower-end GPUs

**Comment by nitaku** [comment]
This had to be done, eventually. It is not critical for a minimal release though.

**Comment by nitaku** [comment]
If the frame rate drops too much, controls are altered, especially wrt rotating the ship. This has more serious implications that it seemed as first.

**Comment by salvob41** [comment]
Closed thanks to #895
