### ISSUE TITLE
Score bars sometimes get stuck in the middle of changing position

### ISSUE THREAD

**Issue by nitaku** [notapixelstudio/superstarfighter#679]

**Comment by salvob41** [comment]
what do you mean?

**Comment by nitaku** [comment]
during the bar sorting animation, sometimes a bar get stuck behind another one. it has exactly the same vertical position, so I suspect the bar index to be wrong

**Comment by nitaku** [comment]
especially in the new bump minigame

**Comment by nitaku** [comment]
There's a super simple solution for this - disable the sorting animation altogether.
This method has a few pros: it is easier for a player to quickly find their bar if they keep the same position, it helps streamers putting their names somewhere, it requires almost no work from our part.
The con is that the animation is nice to see for spectators, and it conveys "competition" in a very poignant way. Players are probably too focused on the battlefield to see the animation of bars, so it's not that relevant for them.
