### ISSUE TITLE
Ships: respawn

### ISSUE THREAD

**Issue by salvob41** [notapixelstudio/superstarfighter#69]

**Comment by salvob41** [comment]
Right now we remove the ship and add it aftwerwards.
It is actually better if we use `queue_free()` and then create a new one copying all it needs.

**Comment by nitaku** [comment]
I believe this is done for now? It was very satisfactory in yesterday's testing session.

**Comment by salvob41** [comment]
I believe that commit 7c3be354177792808a22bb61fc312d6c89c58c54 fixed last mentioned problem. 
So let's close this
