### ISSUE TITLE
New introduction for a minigame

### ISSUE THREAD

**Issue by salvob41** [notapixelstudio/superstarfighter#691]
There should be a nice and smooth animation to the transition from map to the minigame chosen.. 

These could be the step. 
- [ ] animation in map with the chosen minigame
- [ ] fade to white (https://www.youtube.com/watch?v=QC_mn2tX6n0) 
- [ ] show name of the game
- [ ] "press to continue ... "
- [ ] show arena 
- [ ] "fu fu fu" for the ships ... 
- [ ] show other elements of the game
- [ ] Show the scope of the game ... 
- [ ] START
- [ ] reactivate all the input

@nitaku

**Comment by nitaku** [comment]
This is not completed, and provides a checklist with things we have to do (or check). I'll reopen this, but I'll close other related issues that are redundant.
