### ISSUE TITLE
Score points

### ISSUE THREAD

**Issue by salvob41** [notapixelstudio/superstarfighter#71]
Needs something that will keep the score

**Comment by salvob41** [comment]
addressed by PR #78

**Comment by salvob41** [comment]
We need to decide wether to count the deaths, or the kills or the collectables

**Comment by nitaku** [comment]
I believe that from now on we should focus on implementing the "take the crown" mode, as it's the only mode that seems fun enough to play. Maybe other modes could be added in the future.
