### ISSUE TITLE
Font overhaul

### ISSUE THREAD

**Issue by nitaku** [notapixelstudio/superstarfighter#734]
The game should use a combination of 2-3 fonts, possibly easy to read but also not too plain. [Bungee](https://www.fontsquirrel.com/fonts/bungee?q%5Bterm%5D=Bungee&q%5Bsearch_check%5D=Y) could be a good one.

**Comment by salvob41** [comment]
fixed by https://github.com/notapixelstudio/superstarfighter/commit/1ea2fd49c4c13a795a57fb47c2debd48386d2d75 
maybe need some tweaks

**Comment by salvob41** [comment]
will reopen if needed
