### ISSUE TITLE
Ship invincible after respawn

### ISSUE THREAD

**Issue by salvob41** [notapixelstudio/superstarfighter#84]

**Comment by salvob41** [comment]
In the first seconds after respawn... Should we add state machine to Ship ?

**Comment by nitaku** [comment]
A state machine for this is an overkill, IMHO

**Comment by salvob41** [comment]
Well, put state variables to determine if you are _invincible_ or not into the code is more bug-prone and basically an oversimplification of a State machine.

**Comment by nitaku** [comment]
Smells like overengineering to me... but I am not against it.

I'd still avoid to introduce huge dependencies like that bloated state machine plugin. And try to keep things simple.

**Comment by salvob41** [comment]
A invincible ship CANNOT: 
- fire
- die
- charge shot
- cause bomb to triggers (?) 

It can only move around

**Comment by nitaku** [comment]
It shouldn't trigger bombs, nor they should lock on the ship while invincible.

**Comment by salvob41** [comment]
in order not to trigger bombs we need to do something a bit complicated: 

https://github.com/notapixelstudio/superstarfighter/blob/5483f10af09ddd697f82c47fae031fcf66efc704/actors/weapons/Bomb.gd#L82

maybe we need to remove the component while in the invincible state?
