### ISSUE TITLE
Cockpit pilots' species

### ISSUE THREAD

**Issue by salvob41** [notapixelstudio/superstarfighter#90]
something like this

http://www.artnet.com/artists/andrew-loomis/fighter-pilot-in-cockpit-buhZ8TrtPfB9KsH5edUL2w2

**Comment by nitaku** [comment]
What's the current use case for this? Where should these images appear?

**Comment by salvob41** [comment]
interface on the screen in the GUI. 
or, more likely, in the gameover screen
